//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationHotelOnline.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ID { get; set; }
        public int RoomTypeID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int NoDays { get; set; }
        public decimal TotalPrice { get; set; }
        public int RoomID { get; set; }
        public int MastarID { get; set; }
    
        public virtual MastarReservation MastarReservation { get; set; }
        public virtual Room Room { get; set; }
        public virtual RoomType RoomType { get; set; }
    }
}
